from turtle import Turtle, Screen
Chinmay = Turtle()
print(Chinmay)
Chinmay.shape("turtle")
Chinmay.color("red")
Chinmay.forward(90)
Chinmay.left(300)
Chinmay.forward(90)
Chinmay.left(300)
Chinmay.forward(90)
Chinmay.left(300)
Chinmay.forward(90)
Chinmay.left(300)
Chinmay.forward(90)
Chinmay.left(300)
Chinmay.forward(90)
Chinmay.left(300)
Chinmay.forward(90)
my_screen = Screen()
print(my_screen.canvheight)
my_screen.exitonclick()
